export const types = {
  LOGIN_ACTION: "LOGIN_ACTION",
  LOGIN_ACTION_SUCCESS: "LOGIN_ACTION_SUCCESS",
  LOGIN_ACTION_FAILED: "LOGIN_ACTION_FAILED",
  UPLOAD_PROFILE_ACTION: "UPLOAD_PROFILE_ACTION",
  UPLOAD_PROFILE_ACTION_SUCCESS: "UPLOAD_PROFILE_ACTION_SUCCESS",
  UPLOAD_PROFILE_ACTION_FAILED: "UPLOAD_PROFILE_ACTION_FAILED",
};
